subroutine manual()
  write(*,'("	     ______________________________________________")')
  write(*,'("")')
  write(*,'("			   OPTOOL USER GUIDE")')
  write(*,'("")')
  write(*,'("	      Carsten Dominik, Michiel Min, and Ryo Tazaki")')
  write(*,'("	     ______________________________________________")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("		       March 2021, version 1.7.3")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("1 Introduction")')
  write(*,'("==============")')
  write(*,'("")')
  write(*,'("  This tool produces complex dust particle opacities right from the")')
  write(*,'("  command line. It is derived from Michiel Min s DHS [OpacityTool] and")')
  write(*,'("  also implements Ryo Tazaki s MMF theory for highly porous aggregates.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("1.1 Capabilities")')
  write(*,'("~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  - stand-alone tool, fully command line driven, no input files need to")')
  write(*,'("    be edited")')
  write(*,'("  - full scattering matrix output in several formats, including for")')
  write(*,'("    RADMC-3D")')
  write(*,'("  - combining materials through mixing into a complex grain with")')
  write(*,'("    porosity")')
  write(*,'("  - /built-in/: a curated collection of materials for applications in")')
  write(*,'("    astronomy")')
  write(*,'("  - external refractive index data can be used just as easily")')
  write(*,'("  - two computational methods: (i) *DHS (Distribution of Hollow")')
  write(*,'("    Spheres)* for /irregular grains/ and /low-porosity/ aggregates.")')
  write(*,'("    Standard *Mie theory* for /perfect spheres/ is available as a")')
  write(*,'("    limiting case. (ii) *MMF (Modified Mean Field)* theory for")')
  write(*,'("    /high-porosity/fractal aggregates/")')
  write(*,'("  -  Python  interface module for plotting and post-processing")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("1.2 Terms of use")')
  write(*,'("~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("   optool  is distributed under the [MIT license] and can be used,")')
  write(*,'("  changed and redistributed freely. The relevant references for this")')
  write(*,'("  tool are listed below.  Depending on which parts of  optool  you are")')
  write(*,'("  using, please reference the corresponding papers.")')
  write(*,'("")')
  write(*,'("  -  optool : [ https://github.com/cdominik/optool.git ]")')
  write(*,'("  - DHS model for irregular grains: [Min et al. 2005, A&A, 432, 909]")')
  write(*,'("  - MMF model for aggregates: [Tazaki & Tanaka 2018, ApJ 860, 79]")')
  write(*,'("  - DIANA standard Opacities: [Woitke, Min et al. 2016, A&A 586, 103]")')
  write(*,'("  - Third party software: [Toon et al. 1981, Applied Optics 20, 3657]")')
  write(*,'("  - References to [refractive index data] used in your particular")')
  write(*,'("    application.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("2 Examples")')
  write(*,'("==========")')
  write(*,'("")')
  write(*,'("  A simple grain made only of the default pyroxene, for the default")')
  write(*,'("  grain size distribution ($a^{-3.5}$ powerlaw from 0.05 to 3000mum), on")')
  write(*,'("  the default wavelength grid (0.05mum to 1cm).")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Include the scattering matrix in the produced output")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr -s")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Reproduce the DIANA standard dust model, using a specific pyroxene")')
  write(*,'("  (70% Mg) and carbon, in a mass ratio 0.87/0.13, and with a porosity of")')
  write(*,'("  25%.")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr-mg70 0.87  c 0.13  -p 0.25")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  List the built-in materials")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool -c")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Add a water ice mantle (built-in data from Warren+08) that is 20% of")')
  write(*,'("  the core mass")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr-mg70 0.87  c 0.13  -m h2o-w 0.2  -p 0.25")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Like the previous example, but use ice refractive index data from a")')
  write(*,'("  separate file.")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr-mg70 0.87  c 0.13  -p 0.25  -m data/ice_hudgins.dat 0.2")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Pure water ice grains in a narrow size distribution from 1 to 3")')
  write(*,'("  microns, with 15 sample sizes following an $f(a)\propto a^{-2.5}$")')
  write(*,'("  powerlaw size distribution. Also, restrict the wavelength range to")')
  write(*,'("  10-100mum, and turn off DHS to get perfect spheres.")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool h2o  -a 1 3 2.5 15  -l 10 100 -fmax 0")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  For silicon carbide, compute the opacity of a single grains size")')
  write(*,'("  (2.5mum) at lambda=8.9mum.")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool -a 2.5 -l 8.9 sic")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Represent the default dust model (DIANA, you also get this when you do")')
  write(*,'("  not give any materials at all) in 42 grain sizes, and produce input")')
  write(*,'("  files for RADMC-3D, one for each grain size, with full scattering")')
  write(*,'("  matrix, chopping 3 degrees from the scattering peak.")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool -na 42 -d -s -radmc -chop 3")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  Use MMF to compute the opacities of dust aggregates made of pyroxene")')
  write(*,'("  monomers.  Use a monomer radius of 0.3 mum to construct aggregates")')
  write(*,'("  with compact-volume radii between 10 and 30 mum, and a filling factor")')
  write(*,'("  of 5%")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr  -a 10 30  -mmf 0.3 0.05")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  As before, but fix the fractal dimension $D_f=1.9$ instead of setting")')
  write(*,'("  the filling factor")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | optool pyr  -a 10 30  -mmf 0.3 1.9")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("3 Compiling  optool ")')
  write(*,'("====================")')
  write(*,'("")')
  write(*,'("  On most systems, you can download and compile  optool  with these")')
  write(*,'("  simple steps, using the freely available GNU FORTRAN compiler")')
  write(*,'("  [ gfortran ].")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | git clone https://github.com/cdominik/optool.git")')
  write(*,'("  | cd optool")')
  write(*,'("  | make multi=true")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  The executable is called  optool , and you should put it on your")')
  write(*,'("  execution path.  To use the [Intel fortran compiler], to use multiple")')
  write(*,'("  cores for speed (highly recommended if your system supports it), or to")')
  write(*,'("  be able to write FITS files[1], use one or more of the following")')
  write(*,'("  parameters during compilation:")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | make ifort=true        # use the Intel fortran compiler iFort")')
  write(*,'("  | make multi=true        # enable multicore support")')
  write(*,'("  | make  fits=true        # add support for writing FITS files[1]")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("  You can also find binaries for Mac and Linux at [my homepage].")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4 Command line arguments")')
  write(*,'("========================")')
  write(*,'("")')
  write(*,'("   -h   ")')
  write(*,'("        Show a compact help message about command line options.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4.1 Grain composition")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  If no composition is specified, the default is *-c pyr 0.87 -c c 0.13")')
  write(*,'("  -p 0.25*.")')
  write(*,'("")')
  write(*,'("   -c ")')
  write(*,'("        List available built-in materials (the keys for the *-c* and")')
  write(*,'("        *-m* options).")')
  write(*,'("")')
  write(*,'("   [-c] KEY-or-FILE [MFRAC] ")')
  write(*,'("        Specify a material to include in the grain.   KEYorFILE  can be")')
  write(*,'("        the [key for a builtin material], or the path to an  lnk ")')
  write(*,'("        file.  MFRAC  is the /mass/ fraction (default 1.0) of the")')
  write(*,'("        material. You can give up to 10 materials to build up the grain.")')
  write(*,'("        Mass fractions do not have to add up to one, they will be")')
  write(*,'("        renormalized.  All materials will be mixed together using the")')
  write(*,'("        /Bruggeman/ rule, and vacuum can be added through the")')
  write(*,'("        porosity. A *-c* switch before each  KEY-or-FILE  is optional.")')
  write(*,'("")')
  write(*,'("   -m KEY-or-FILE [MFRAC] ")')
  write(*,'("        Like *-c*, but place this material into the grain")')
  write(*,'("        mantle. Multiple mantle materials will be mixed using the")')
  write(*,'("        Bruggeman rule, and than that mix will be added to the core")')
  write(*,'("        using the /Maxwell-Garnett/ rule.  The *-m* is /not/ optional,")')
  write(*,'("        it must be present.")')
  write(*,'("")')
  write(*,'("   -p POROSITY [P_MANTLE] ")')
  write(*,'("        Porosity, the /volume/ fraction of vacuum, a number smaller than")')
  write(*,'("        1.  The default is 0.  A single value will apply to both core")')
  write(*,'("        and mantle, but a second value will be specific for the mantle")')
  write(*,'("        (and may be 0).")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4.2 Grain geometry and computational method")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  If no method is explicitly specified, the default is *-dhs 0.8*, i.e.")')
  write(*,'("  DHS with f_max=0.8.")')
  write(*,'("")')
  write(*,'("   -dhs [FMAX] ")')
  write(*,'("        Use the /Distribution of Hollow Spheres/ (DHS, Min+ 2005)")')
  write(*,'("        approach to model deviations from perfect spherical symmetry and")')
  write(*,'("        low-porosity aggregates. Spheres with inner holes with volume")')
  write(*,'("        fractions between 0 and f_max (default 0.8) are averaged to")')
  write(*,'("        mimic irregularities.  f_max=0 means to use solid spheres (Mie")')
  write(*,'("        theory), i.e. perfectly regular grains. For backward")')
  write(*,'("        compatibility, *-fmax* can be used instead of *-dhs*.")')
  write(*,'("")')
  write(*,'("   -mie ")')
  write(*,'("        Do a standard /Mie/ calculation for perfect spheres. This is")')
  write(*,'("        short for *-dhs 0* .")')
  write(*,'("")')
  write(*,'("   -mmf [A0 [DFRAC-OR-FILL]] ")')
  write(*,'("        Use /Modified Mean Field/ theory (MMF, Tazaki & Tanaka 2018) to")')
  write(*,'("        compute opacities of highly porous or fractal aggregates.  *-c*,")')
  write(*,'("        *-m*, and *-p* now determine the composition of monomers.   A0 ")')
  write(*,'("        is the monomer radius (default 0.1mum).  Particles will be")')
  write(*,'("        aggregates with a /compact size/ given by the *-a* switch,")')
  write(*,'("        giving rise to $N=a^3/a_0^3$ monomers. When  DFRAC-OR-FILL  is")')
  write(*,'("        greater than 1, it specifies the /fractal dimension/.  When it")')
  write(*,'("        is less than 1, it is interpreted as the /volume filling factor/")')
  write(*,'("        of the aggregates instead. The default is 0.2, corresponding to")')
  write(*,'("        a 20% filling factor.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4.3 Grain size distribution")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("   -a AMIN [AMAX [APOW [NA]]] ")')
  write(*,'("        Specify (minimum) grain radius, and optionally maximum grain")')
  write(*,'("        radius, the size distribution powerlaw and the number of size")')
  write(*,'("        bins.  You may also use options to set individual values with")')
  write(*,'("        *-amin*, *-amax*, *-apow*, *-na*. The defaults are 0.05 mum,")')
  write(*,'("        3000 mum, 3.5, and /10 per size decade with a fixed minimum of")')
  write(*,'("        5/, respectively.  If only a single size is specified with *-a*,")')
  write(*,'("        then a_max=a_min and n_a=1 are implied.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4.4 Wavelength grid")')
  write(*,'("~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("   -l LMIN [LMAX [NLAM]] ")')
  write(*,'("        Specify the (minimum) wavelength, and optionally the maximum")')
  write(*,'("        wavelength and the number of wavelengths points for the")')
  write(*,'("        construction of the wavelength grid.  The default values are")')
  write(*,'("        0.05 mum, 10000 mum, and 300, respectively.  You may also use")')
  write(*,'("        the options *-lmin*, *-lmax*, and *-nlam* (or *-nl*) to set")')
  write(*,'("        individual values.  If only one wavelength is specified with")')
  write(*,'("        *-l*, then lambda_max=lambda_min and n_lambda=1 are implied.")')
  write(*,'("")')
  write(*,'("   -l FILE ")')
  write(*,'("        Read the wavelength grid from  FILE .  The file may start with")')
  write(*,'("        comment lines, and the first non-comment line needs to contain")')
  write(*,'("        the number of wavelength values in the data block below it. In")')
  write(*,'("        the data block, the first column is expected to hold the")')
  write(*,'("        wavelength values, in mum. In particular, an [ lnk ] file could")')
  write(*,'("        be used here.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("4.5 Controlling the output")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  The standard output is the file  dustkappa.dat , with the opacities")')
  write(*,'("  and the asymmetry parameter /g/. The following options control and")')
  write(*,'("  extend the [output].")')
  write(*,'("")')
  write(*,'("   -o [DIR] ")')
  write(*,'("        Put the output files in directory  DIR  instead of the current")')
  write(*,'("        working directory.  ./output  will be used if *-o* is present")')
  write(*,'("        but  DIR  is not specified.")')
  write(*,'("")')
  write(*,'("   -s [NANG] ")')
  write(*,'("        Include the full scattering matrix in the output.  NANG  can")')
  write(*,'("        optionally specify the number of equally-spaced [angular grid")')
  write(*,'("        points] to cover the range of angles between 0 and 180 degrees.")')
  write(*,'("        The default for  NANG  is 180 and should normally be just fine.")')
  write(*,'("")')
  write(*,'("   -chop [NDEG] ")')
  write(*,'("        Cut out the first  NDEG  (2 if unspecified) degrees of the")')
  write(*,'("        [forward scattering peak] and compensate by a reduction in the")')
  write(*,'("        scattering cross section.")')
  write(*,'("")')
  write(*,'("   -d [NSUB] ")')
  write(*,'("        Divide the computation up into  NA  parts to produce a file for")')
  write(*,'("        each grain size.  Each size will actually be an average over a")')
  write(*,'("        small range of  NSUB  grains around the real size, to smear out")')
  write(*,'("        resonances.  The default for  NSUB  is 5.")')
  write(*,'("")')
  write(*,'("   -fits ")')
  write(*,'("        Write  dustkappa.fits  with the absorption cross sections and")')
  write(*,'("        scattering matrix elements, instead of ASCII output.  With the")')
  write(*,'("         -d  switch,  NA  files will be written.")')
  write(*,'("")')
  write(*,'("   -radmc [LABEL] ")')
  write(*,'("        RADMC-3D uses a different angular grid and normalization for the")')
  write(*,'("        [scattering matrix], so the output has to be adapted for it.")')
  write(*,'("        The extension of the files will be changed to  .inp , and if you")')
  write(*,'("        specify  LABEL , it will be used in the file name(s).")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("5 Material properties")')
  write(*,'("=====================")')
  write(*,'("")')
  write(*,'("   optool  needs refractive index data to work.  For your convenience, a")')
  write(*,'("  useful list of materials is compiled into  optool . You can also find")')
  write(*,'("  and use other data.  No matter where the data is from, you should")')
  write(*,'("  /always/ cite the original laboratory papers.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("5.1 Built-in materials")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  To access one of the built-in materials, specify the corresponding key")')
  write(*,'("  string like  pyr-mg70 . In each material class we have selected a")')
  write(*,'("  useful default, accessible with an even simpler generic key (for")')
  write(*,'("  example,  pyr  is an alias for  pyr-mg70 ). Most of the built-in")')
  write(*,'("  refractive index datasets have a wide wavelength coverage - the few")')
  write(*,'("  exceptions are highlighted by bold-face numbers.  If a material is")')
  write(*,'("  being used outside of the measured region,  optool  will still")')
  write(*,'("  function, using extrapolated optical properties.")')
  write(*,'("")')
  write(*,'("  Even the limited number of materials we have selected to include with")')
  write(*,'("   optool  can be daunting. To get started with some kind of standard")')
  write(*,'("  opacity, we recommend to work with pyroxene \fbox{pyr}, carbon")')
  write(*,'("  \fbox{c}, and (at low temperaturs) water ice \fbox{h2o}.")')
  write(*,'("")')
  write(*,'("  -c Key      -c Key      Material                 State         max   Referenc")')
  write(*,'(" generic     full key                                         g/cmum           ")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'("             pyr-mg100   MgSiO_3                  amorph        2500  [Dorschne")')
  write(*,'("             pyr-mg95    Mg_0.95  Fe_0.05  SiO_3  amorph        2500  [Dorschne")')
  write(*,'("             pyr-mg80    Mg_0.8  Fe_0.2  SiO_3    amorph         500  [Dorschne")')
  write(*,'(" \fboxpyr    pyr-mg70    Mg_0.7  Fe_0.3  SiO_3    amorph        3500  [Dorschne")')
  write(*,'("             pyr-mg60    Mg_0.6  Fe_0.4  SiO_3    amorph         500  [Dorschne")')
  write(*,'("             pyr-mg50    Mg_0.5  Fe_0.5  SiO_3    amorph         500  [Dorschne")')
  write(*,'("             pyr-mg40    Mg_0.4  Fe_0.6  SiO_3    amorph         500  [Dorschne")')
  write(*,'(" ens         pyr-c-mg96  Mg_0.96  Fe_0.04  SiO3   cryst          99   [Jäger+9")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'(" ol          ol-mg50     MgFeSiO_4                amorph        3500  [Dorschne")')
  write(*,'("             ol-mg40     Mg_0.8 Fe_1.2 SiO_4      amorph        3500  [Dorschne")')
  write(*,'(" for         ol-c-mg100  Mg_2 SiO_4               cryst         3250  [Steyer+7")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'("             astrosil    MgFeSiO4                 mixed          1e5  [Draine+0")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'(" \fboxc      c-z         C                        amorph?        1e4  [Zubko+96")')
  write(*,'("             c-p         C                        amorph         800  [Preibisc")')
  write(*,'(" gra         c-gra       C graphite               cryst        2.000  [Draine+0")')
  write(*,'(" org         c-org       CHON organics            amorph         1e5  [Henning+")')
  write(*,'("             c-nano      C nano-diamond           cryst          10   [Mutschke")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'(" iron        fe-c        Fe                       metal         71e5  [Henning+")')
  write(*,'("             fes         FeS                      metal         41e5  [Henning+")')
  write(*,'("             sic         SiC                      cryst         3000  [Laor93] ")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'(" qua         sio2        SiO_2                    amorph        2500  [Kitamura")')
  write(*,'(" cor         cor-c       Al_2  O_3                cryst          40   [Koike+95")')
  write(*,'("-------------------------------------------------------------------------------")')
  write(*,'(" \fboxh2o    h2o-w       Water ice                cryst         02e6  [Warren+0")')
  write(*,'(" co2         co2-w       CO_2 ice                 cryst          2e5  [Warren+8")')
  write(*,'(" nh3         nh3-m       NH_3 ice                 cryst         0200  [Martonch")')
  write(*,'(" co          co-a        CO ice                   amorph        0.8   [Palumbo+")')
  write(*,'("             co2-a/c     CO_2 ice                 am/cr          20   [Gerakine")')
  write(*,'("             ch4-a/c     CH_4 ice                 am/cr         020   [Gerakine")')
  write(*,'("             ch3oh-a/c   CH_3  OH ice             am/cr    0.78/124   [Gerakine")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("5.2 External refractory index files ( lnk  files)")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("   optool  can use external refractive index data in files with the")')
  write(*,'("  following format:")')
  write(*,'("  - The file may start with several comment lines (lines starting with")')
  write(*,'("     ! ,  # , or  * ).")')
  write(*,'("  - The next line contains two numbers, the number of wavelengths")')
  write(*,'("    $n_\lambda$ and the specific density rho of the material in")')
  write(*,'("    g/cm^{3}.")')
  write(*,'("  - The remaining lines should form three columns of data: lambda[mum]")')
  write(*,'("    (sorted either up or down), and the real and imaginary parts of the")')
  write(*,'("    refractive index, $n$ and $k$.")')
  write(*,'("")')
  write(*,'("  You can find additinal refractive index data [here], in databases like")')
  write(*,'("  the [Jena database], and associated with original papers in the")')
  write(*,'("  literature. Don t forget to add the line with $n_\lambda$ and rho!  If")')
  write(*,'("  that is not possible,  optool  will count the lines and you can")')
  write(*,'("  specify the density after the mass fraction, like this:  optool -c")')
  write(*,'("  path/to/file.lnk 0.7 3.42 .")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("6 Output files")')
  write(*,'("==============")')
  write(*,'("")')
  write(*,'("  dustkappa.dat")')
  write(*,'("        This is an ASCII file containing the basic opacity results. It")')
  write(*,'("        starts with a comment section describing the dust model,")')
  write(*,'("        followed by the format number (3, currently), followed by the")')
  write(*,'("        number of wavelengths in the grid, both on lines by themselves.")')
  write(*,'("        Then follows a block with these columns:")')
  write(*,'("")')
  write(*,'("        1. wavelength lambda [micron]")')
  write(*,'("        2. mass absorption cross section kappa_abs [cm^2/g]")')
  write(*,'("        3. mass scattering cross section kappa_sca [cm^2/g]")')
  write(*,'("        4. asymmetry parameter /g/")')
  write(*,'("")')
  write(*,'("  dustkapscatmat.dat")')
  write(*,'("        ASCII file with cross sections and full scattering matrix. It is")')
  write(*,'("        an extended version of the  dustkappa.dat  file.  This file has")')
  write(*,'("        a format number (0), the number of wavelengths and then the")')
  write(*,'("        number of angular points after the comment section.  After en")')
  write(*,'("        empty line, this is followed by the same block of wavelengths")')
  write(*,'("        and opacities as described above for the  dustkappa.dat  file.")')
  write(*,'("        Another empty line is followed by a list of the grid angles, yet")')
  write(*,'("        another empty line, and then the scattering matrix elements for")')
  write(*,'("        all wavelengths and all angles. The comment section at the start")')
  write(*,'("        of the file shows the structure in a formal way.  See [the")')
  write(*,'("        appendix] for information about the normalization of the")')
  write(*,'("        scattering matrix and about the angular grid that is used for")')
  write(*,'("        it.  Also, see the  -radmc  switch which will modify[2] the")')
  write(*,'("        output to make sure it can be used as an input file for")')
  write(*,'("        [RADMC-3D].")')
  write(*,'("")')
  write(*,'("  dustkappa.fits")')
  write(*,'("        The FITS-file (ending in ’.fits’) is written instead of the")')
  write(*,'("        ASCII output when using the  -fits  switch. It has two HDU")')
  write(*,'("        blocks. The first block contains the cross sections per unit")')
  write(*,'("        mass. This is an n_lambda * 4 matrix with these columns:")')
  write(*,'("")')
  write(*,'("        1. wavelength in [mum]")')
  write(*,'("        2. mass extinction cross section kappa_ext in [cm^2/g]")')
  write(*,'("        3. mass absorption cross section kappa_abs in [cm^2/g]")')
  write(*,'("        4. mass scattering cross section kappa_sca in [cm^2/g]")')
  write(*,'("")')
  write(*,'("        The second HDU block contains the scattering matrix elements. It")')
  write(*,'("        is a n_lambda * 6 * n_ang matrix, containing the 6 elements of")')
  write(*,'("        the scattering matrix for n_ang equidistant scattering angles")')
  write(*,'("        from forward scattering (element 0) to backward scattering")')
  write(*,'("        (element n_ang-1), for each wavelength value. The stored matrix")')
  write(*,'("        elements are F_11, F_12, F_22, F_33, F_34, and F_44.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("7 Python interface")')
  write(*,'("==================")')
  write(*,'("")')
  write(*,'("   optool  comes with a [ python ] module  optool.py  that runs  optool ")')
  write(*,'("  in the background[3] and puts all computed quantities as  numpy ")')
  write(*,'("  arrays into a python object.  This makes it straight forward to")')
  write(*,'("  inspect and further process the output, for example to produce custom")')
  write(*,'("  opacity files for use in a radiative transfer tool. Here is how to use")')
  write(*,'("  the module:")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | import optool")')
  write(*,'("  | p = optool.particle( ~/bin/optool pyr 0.8 -m ice 0.2 -na 24 -d )")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("  The argument to  optool.particle()  must be a valid shell command[4]")')
  write(*,'("  to run  optool , if necessary with the full path to the  optool ")')
  write(*,'("  binary.  Depending on the presence of the  optool  s *-d* switch, the")')
  write(*,'("  command will produce opacities either for $n_p=1$ particle, or for")')
  write(*,'("  $n_p=n_a$ particles. Most of the attributes (with the exception of the")')
  write(*,'("  global wavelength and angular grids) will therefore be arrays with the")')
  write(*,'("  first dimension equal to $n_p$, even if $n_p=1$. The resulting object")')
  write(*,'("  will have the following attributes:")')
  write(*,'("")')
  write(*,'("   *Attribute*         *Type/Shape*           *Quantity*                                      ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    cmd                 string                The full command given in the particle() call   ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    radmc               boolean               Output follows RADMC conventions                ")')
  write(*,'("    scat                boolean               Scattering matrix is available                  ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    nlam                int                   Number of wavelength points                     ")')
  write(*,'("    lam                 float[nlam]           The wavelength grid                             ")')
  write(*,'("    nang                int                   Number of scattering angles                     ")')
  write(*,'("    scatang             float[nang]           The angular grid                                ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    materials           [[[...]...]... ]      Lists with [location,m_{frac},rho,material]     ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    np                  int                   Number of particles, either 1 or (with -d) n_a  ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    fmax                float[np]             Maximum volume fraction of vacuum for DHS       ")')
  write(*,'("    pcore ,  pmantle    float[np]             Porosity of the core/mantle material            ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    amin ,  amax        float[np]             min/max grain size used for each particle       ")')
  write(*,'("    nsub                int[np]               Number of sizes averaged for each particle.     ")')
  write(*,'("    apow                float[np]             Negative size distribution power law (e.g. 3.5) ")')
  write(*,'("    a1 ,  a2 ,  a3      fload[np]             Mean <a>, <a^2>, and <a^3> of the particle      ")')
  write(*,'("    rho                 float[np]             Specific density of grains                      ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    kabs,ksca,kext      float[np,nlam]        Absorption,scattering,extinction cross section  ")')
  write(*,'("    gsca                float[np,nlam]        Asymmetry parameter                             ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    f11 , ...,  f44     float[np,nlam,nang]   Scattering matrix element F_11, ... ,F_44       ")')
  write(*,'("    chop                float[np]             Degrees chopped off forward scattering          ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    plot()              method                Plot the cross sections and matrix elements     ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    computemean()       method                Compute Planck/Rosseland mean opacities         ")')
  write(*,'("    tmin,tmax,ntemp     float,float,int       Temperature grid for mean opacities             ")')
  write(*,'("    temp                float[ntemp]          Temperatures used for mean opacities            ")')
  write(*,'("    kplanck,kross       float[np,ntemp]       Mean opacities, after calling  computemean()    ")')
  write(*,'("  --------------------------------------------------------------------------------------------")')
  write(*,'("    norm                string                Current scattering matrix normalization         ")')
  write(*,'("    scatnorm()          method                Check/change scat. matrix normalization         ")')
  write(*,'("")')
  write(*,'("  <file:./maint/inspect.png>")')
  write(*,'("")')
  write(*,'("  The  plot()  method is used like this:")')
  write(*,'("  ,----")')
  write(*,'("  | p.plot()")')
  write(*,'("   ----")')
  write(*,'("  It will produce the following plots:")')
  write(*,'("  - a plot showing the opacities kappa_abs, kappa_sca, and kappa_ext as")')
  write(*,'("    a function of wavelength, along with the asymmetry parameter /g/ (on")')
  write(*,'("    a linear y-scale).  Note that the blue /g/ curve does not havex its")')
  write(*,'("    own axis, imagine the full /y/ axis going from 0 to 1 for /g/.")')
  write(*,'("  - a plot showing the scattering matrix elements as a function of")')
  write(*,'("    scattering angle, with sliders to go through grain sizes and")')
  write(*,'("    wavelengths.  When interpreting the y axis, note that we plot the")')
  write(*,'("    positive/negative $\log_{10}$ of positive/negative matrix elements,")')
  write(*,'("    compressing the range from $10^{-2}$ to $10^2$ into a line (use the")')
  write(*,'("    grey lines as a guide, ignore the y-axis labels).")')
  write(*,'("  - If the  computemean  method has been called first, the mean")')
  write(*,'("    opacities kappa_Planck and kappa_Ross are shown in a separate plot.")')
  write(*,'("    The mean opacities are per unit of grain mass, so please apply a")')
  write(*,'("    dust-to-gas mass ratio to obtain opacities for a gas-dust mixture.")')
  write(*,'("")')
  write(*,'("  You can also use /particle arithmetic/ (multiplying  particle  objects")')
  write(*,'("  with factors and adding them - this is implemented in a way that it")')
  write(*,'("  works correctly also for the scattering matrix), for example to")')
  write(*,'("  produce opacites for a mixture of different grains or scale opacities")')
  write(*,'("  using a dust-to-gas ratio:")')
  write(*,'("")')
  write(*,'("  ,----")')
  write(*,'("  | p1 = optool.particle( optool -a 0.01 0.3 pyr-mg70 )      # silicate grains")')
  write(*,'("  | p2 = optool.particle( optool -a 0.03 0.1 c-z )           # carbon grains")')
  write(*,'("  | p  = 0.75*p1 + 0.25*p2   # add with mass fractions")')
  write(*,'("  | p  = p * 0.01            # apply dust-to-gas ratio -> opacity per gas mass")')
  write(*,'("   ----")')
  write(*,'("")')
  write(*,'("  \appendix")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("8 Units")')
  write(*,'("=======")')
  write(*,'("")')
  write(*,'("  Due to conventions in our field, the input and output of  optool  uses")')
  write(*,'("  the following units")')
  write(*,'("  - *microns* for grain sizes and wavelengths")')
  write(*,'("  - *g/cm^3* for mass densities of materials")')
  write(*,'("  - *cm^2 g^-1* for opacities kappa_abs, kappa_sca, and kappa_ext")')
  write(*,'("  - *sr^-1* or *cm^2 g^-1 sr^-1* for the scattering matrix elements, see")')
  write(*,'("    below.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("9 Scattering Matrix: The fine print")')
  write(*,'("===================================")')
  write(*,'("")')
  write(*,'("9.1 Phase function normalization")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  A number of different normalizations for the scattering matrix are")')
  write(*,'("  being used in the literature and in computational tools. The")')
  write(*,'("  differences are significant, and it is important to be aware of the")')
  write(*,'("  choice. For  optool  we are using a convention ([Hovenier (2004)]) in")')
  write(*,'("  which the average over all directions of the 1-1 element of the")')
  write(*,'("  scattering matrix equals unity, i.e.")')
  write(*,'("")')
  write(*,'("  \begin{equation}")')
  write(*,'("  \label{eq:1}")')
  write(*,'("  \oint_{(4\pi)} F_{11}(\lambda,\Theta) d\Omega = ")')
  write(*,'("  2\pi \int_{-1}^{1} F_{11}(\lambda,\mu) {\rm d}\mu= 4\pi \quad ,")')
  write(*,'("  \end{equation}")')
  write(*,'("")')
  write(*,'("  with $\mu=\cos\Theta$.  optool  can also produce output for [RADMC-3D]")')
  write(*,'("  which uses instead")')
  write(*,'("")')
  write(*,'("  \begin{equation}")')
  write(*,'("  \label{eq:2}")')
  write(*,'("  \oint_{(4\pi)} Z_{11}(\lambda,\Theta) d\Omega =")')
  write(*,'("  2\pi \int_{-1}^{1} Z_{11}(\lambda,\mu) {\rm d}\mu =")')
  write(*,'("   \kappa_{\rm sca}(\lambda) \quad .")')
  write(*,'("  \end{equation}")')
  write(*,'("")')
  write(*,'("  The books by Bohren & Huffman and by Mishchenko use different")')
  write(*,'("  normalizations again. You can change the normalization of the")')
  write(*,'("  scattering matrix in the python interface with the  scatnorm() ")')
  write(*,'("  method. By default, it checks the current normalization.  Using an")')
  write(*,'("  argument   r  ,   b  ,   m  , or   h   will modify the normalization.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("9.2 Forward-scattering peak")')
  write(*,'("~~~~~~~~~~~~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("  Particles that are much larger than the wavelength of the considered")')
  write(*,'("  radiation can show extreme forward scattering, where much of the")')
  write(*,'("  /scattered/ radiation is sent into just a few degrees around the")')
  write(*,'("  forward direction.  This can be difficult to handle for radiative")')
  write(*,'("  transfer codes which have limited angular resolution or limited")')
  write(*,'("  sampling. [MCMax3D] has the  nspike  keyword to deal with this")')
  write(*,'("  issue. Other tools (e.g. RADMC-3D) require this to be taken care of by")')
  write(*,'("  the process that creates the opacity files.  The  -chop  switch")')
  write(*,'("  specifies a number of degrees around the forward scattering")')
  write(*,'("  direction. Inside that cone, the scattering matrix gets limited to the")')
  write(*,'("  value at the edge of the cone. To compensate and ensure energy")')
  write(*,'("  conservation, the scattering cross section will be reduced")')
  write(*,'("  accordingly. As a result, the radiation that would be /scattered/ into")')
  write(*,'("  this narrow range of angles will be treated as if it did have /no")')
  write(*,'("  interaction at all/ with the grain.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("9.3 Angular grid")')
  write(*,'("~~~~~~~~~~~~~~~~")')
  write(*,'("")')
  write(*,'("   optool  uses an angular grid in one degree steps from 0 to 180")')
  write(*,'("  degrees.  The full degrees are the cell /interfaces/ of that")')
  write(*,'("  grid.  optool  computes the scattering matrix at the cell /midpoints/,")')
  write(*,'("  i.e. at 0.5degree, 1.5degree etc to 179.5degree, for a total of 180")')
  write(*,'("  values.  The scattering matrix is normalized in this way, so that a")')
  write(*,'("  numerical integral gives the correct result.")')
  write(*,'("")')
  write(*,'("  RADMC-3D requires the values of the scattering matrix on the cell")')
  write(*,'("  /boundaries/, so at 0degree, 1degree etc to 180degree, for a total of")')
  write(*,'("  181 values.  For the input files for RADMC-3D, we interpolate and")')
  write(*,'("  extend the computed values to the cell boundaries.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("10 Overview of optical properties")')
  write(*,'("=================================")')
  write(*,'("")')
  write(*,'("  This grid plot shows the imaginary parts of all built-in materials, in")')
  write(*,'("  the wavelength range from 0.05 to 300 mum.")')
  write(*,'("")')
  write(*,'("  <file:./maint/all_k.pdf>")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("11 How to ingest refractive index data for another material")')
  write(*,'("===========================================================")')
  write(*,'("")')
  write(*,'("  Using external refractive index data means that you have to keep track")')
  write(*,'("  of where those files are.  It can be convenient to compile your")')
  write(*,'("  favorite materials into  optool , so that accessing them will be as")')
  write(*,'("  simple as using the [built-in materials].  Here is how to do that:")')
  write(*,'("")')
  write(*,'("  1. Give your  lnk  file a name exactly like")')
  write(*,'("      pyr-mg70-Dorschner1995.lnk , where the start of the name")')
  write(*,'("     ( pyr-mg70 ) is the key to access the material and  Dorschner1995 ")')
  write(*,'("     (the text after the final  - ) is the reference.")')
  write(*,'("  2. Put this file into the  lnk_data  directory.")')
  write(*,'("  3. Optionally edit  lnk_data/lnk-help.txt , so that [ optool -c ] will")')
  write(*,'("     list the new material.  Note that, in order to define /generic")')
  write(*,'("     keys/, optool looks for pairs that look like  genkey -> fullkey  in")')
  write(*,'("     this file.")')
  write(*,'("  4. Run  make ingest  to update  optool_refind.f90 , now with your new")')
  write(*,'("     material.")')
  write(*,'("  5. Recompile and install the code.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("12 Internals")')
  write(*,'("============")')
  write(*,'("")')
  write(*,'("  This appendix describes some key aspects of the internal workings of")')
  write(*,'("  the code.")')
  write(*,'("")')
  write(*,'("  Refractive Index Data")')
  write(*,'("        Measured refractive index data is obtained from data compiled")')
  write(*,'("        into the code, or read-in from a file.  That data is then")')
  write(*,'("        interpolated and extrapolated onto the wavelength grid requested")')
  write(*,'("        for the computation. Extrapolation toward short wavelengths is")')
  write(*,'("        done keeping the refractive indices constant.  Extrapolation")')
  write(*,'("        toward long wavelengths assumes that the last two measured data")')
  write(*,'("        points define a powerlaw. Interpolation in the measured grid is")')
  write(*,'("        done using double-logarithmic interpolation.")')
  write(*,'("")')
  write(*,'("  Mixing")')
  write(*,'("        Once the refractive index for all involved materials is")')
  write(*,'("        available, the core and the mantle mixtures are created")')
  write(*,'("        independently, using the Bruggeman rule.  Mass fractions are")')
  write(*,'("        converted into volume fractions, and porosity is implemented")')
  write(*,'("        using vacuum as an additional material.  The subroutine doing")')
  write(*,'("        the mixing uses an iterative procedure that is very stable, also")')
  write(*,'("        for a large number of components.")')
  write(*,'("        If there is a mantle, the Maxwell Garnett rule is applied with")')
  write(*,'("        the core being treated as an inclusion inside a mantle matrix.")')
  write(*,'("")')
  write(*,'("  DHS")')
  write(*,'("        In order to simulate irregularities in grains (irregular shapes,")')
  write(*,'("        or the properties of low-porosity aggregates),  optool  averages")')
  write(*,'("        the opacities of grains with an inner empty region, over a range")')
  write(*,'("        of volume fractions of this inner region between 0 and $f_{\rm")')
  write(*,'("        max}$.  The subroutine used to compute the opacities and")')
  write(*,'("        scattering matrix elements for these structures is  DMiLay ")')
  write(*,'("        (Toon & Ackerman 1981).  When the size parameter $x=2 \pi")')
  write(*,'("        a/\lambda$ exceeds a value of 10^4, no DHS averaging is used.  A")')
  write(*,'("        standard Mie calculation is performed, using the routine")')
  write(*,'("         MeerhoffMie  (reference missing), for a fixed size parameter of")')
  write(*,'("        5000, with proper scaling to the actual size of the particle.")')
  write(*,'("")')
  write(*,'("  MMF")')
  write(*,'("        To construct fluffy/fractal aggregates,  optool  needs the")')
  write(*,'("        number of monomers $N$, the fractal dimension $D_f$, and a")')
  write(*,'("        scaling factor $k_f$ which are related to the radius of gyration")')
  write(*,'("        $R_g$ of the aggregate by")')
  write(*,'("        \begin{equation}")')
  write(*,'("         N=k_f\left(\frac{R_g}{a_0}\right)^{D_f}")')
  write(*,'("        \end{equation}")')
  write(*,'("        The size $a$ of the particles as specified by the *-a* switch is")')
  write(*,'("        interpreted as the /compact/ size of all material in the")')
  write(*,'("        aggregate, so that $N=a^3/a_0^3$, where $a_0$ is the monomer")')
  write(*,'("        radius.  The average volume filling factor $f$ can be expressed")')
  write(*,'("        by $f=N\cdot\left(\sqrt{3/5}\,a_0/R_g\right)^3$.  To determine")')
  write(*,'("        the structure of the aggregates, the user can specify a")')
  write(*,'("        structure parameter.  If that parameter is larger than 1, it is")')
  write(*,'("        interpreted as the /fractal dimension/ $D_f$.  Using a fixed")')
  write(*,'("        fractal dimension means that the volume filling factor will")')
  write(*,'("        decrease with aggregate size.  As an alternative, the structure")')
  write(*,'("        parameter can be less than 1.  In that case, it is interpreted")')
  write(*,'("        as a fixed /volume filling factor/ $f$ that applies to all")')
  write(*,'("        aggregate sizes - with the implication that then the fractal")')
  write(*,'("        dimension increases as a function of size. The fractal prefactor")')
  write(*,'("        $k_f$ is chosen automatically so that the asymptotic density of")')
  write(*,'("        small aggregates is the monomer material density. To force")')
  write(*,'("        another value for the prefactor, it can be given explicitly as")')
  write(*,'("        the third value of the  -mmf  option. The following table")')
  write(*,'("        summarizes the relevant equations.")')
  write(*,'("")')
  write(*,'("               |  -mmf A0 DF     |  -mmf A0 FILL         |  -mmf A0 DF KF                          ")')
  write(*,'("        -------+-----------------+-----------------------+-----------------------------------------")')
  write(*,'("         $f$   | $N^{(D_f-3)/3}$ | *given by user*       | $\sqrt{27/125}\,k_f^{3/D_f}N^{3-1/D_f}$ ")')
  write(*,'("         $D_f$ | *given by user* | $3\ln N\,/\,\ln(N/f)$ | *given by user*                         ")')
  write(*,'("         $k_f$ | $(5/3)^{D_f/2}$ | $(5/3)^{D_f/2}$       | *given by user*                         ")')
  write(*,'("")')
  write(*,'("        With the structure defined,  optool  then applies the formalism")')
  write(*,'("        from Tazaki & Tanaka (2018) to compute cross sections and the")')
  write(*,'("        scattering matrix.  For the determination of the geometrical")')
  write(*,'("        cross section needed in the theory, we use the general")')
  write(*,'("        expressions from Tazaki (2021).   optool  also computes the")')
  write(*,'("        phase shift $\Delta\phi$ caused by the aggregate to check the")')
  write(*,'("        validity of the scattering matrix and the asymmetry parameter.")')
  write(*,'("        If the condition $\Delta\phi<1$ for accurate scattering matrix")')
  write(*,'("        results is violated, a warning will be issued. However, the")')
  write(*,'("        opacities will remain applicable.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("13 Acknowledgments")')
  write(*,'("==================")')
  write(*,'("")')
  write(*,'("  - [Charléne Lefévre] for [SIGMA], for inspiration about grain mantles.")')
  write(*,'("  - [Kees Dullemond] for his python plotting routine  viewarr ")')
  write(*,'("    ([available on github]).")')
  write(*,'("  - [Jeroen Bouwman] for some pointers to refractive index data.")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("14 Bibliography")')
  write(*,'("===============")')
  write(*,'("")')
  write(*,'("  - Bohren, C.F. and Huffman, D.R. 1998, Wiley-VCH,")')
  write(*,'("    /Absorption and Scattering of Light by Small Particles/")')
  write(*,'("  - Chapman et al. 2009, ApJ 690, 496")')
  write(*,'("  - Draine, B., 2003, ApJ 598, 1017")')
  write(*,'("  - Draine, B., 2003, ApJ 598, 1026")')
  write(*,'("  - Dorschner, J. et al. 1995, A&A 300, 503")')
  write(*,'("  - Gerakines, P. and Hudson, R., ApJ 901, 52")')
  write(*,'("  - Henning, Th. and Stognienko, R. 1996, A&A 311,291")')
  write(*,'("  - Hovenier, J, 2004, [Report available on ADS].")')
  write(*,'("  - Jäger, C. et al. 1998, A&A 339, 904")')
  write(*,'("  - Kitamura, R. et al 2007, Applied Optics 46,33, p. 8188")')
  write(*,'("  - Koike, C. et al. 1995, Icarus 114, 203")')
  write(*,'("  - Laor, A. and Draine, B., ApJ 402, 441")')
  write(*,'("  - Lefèvre, C.; Min,M. et al. 2020, A&A (submitted)")')
  write(*,'("  - Martonchik, J. 1984, Applied Optics 23, 541")')
  write(*,'("  - Min, M. et al. 2005, A&A, 432, 909")')
  write(*,'("  - Min, M. et al. 2016, A&A, 585, 13")')
  write(*,'("  - Mishchenko, M. et al. 2002, Cambridge University Press,")')
  write(*,'("    /Scattering, absorption, and emission of light by small particles/")')
  write(*,'("  - Mutschke, H. et al. 2004, A&A 423, 983")')
  write(*,'("  - Okuzumi, S. et al. 2009, ApJ 707, 1247")')
  write(*,'("  - Tazaki, R. et al. 2016, ApJ 823, 70")')
  write(*,'("  - Tazaki, R. & Tanaka, H. 2018, ApJ 860,79")')
  write(*,'("  - Tazaki, R. 2021, submitted")')
  write(*,'("  - Toon, O. & Ackerman,T. 1981, Applied Optics 20, 3657")')
  write(*,'("  - Woitke, P.; Min, M. et al. 2016, A&A 586, 103")')
  write(*,'("  - Palumbo, E. et al. 2006, PCCP 8, 279")')
  write(*,'("  - Preibisch, Th. et al. 1993, A&A 279, 577")')
  write(*,'("  - Steyer, T. 1974, PhD Thesis, The University of Arizona")')
  write(*,'("  - Warren, S. and Brandt, R. 2008, JGRD,113, D14220")')
  write(*,'("  - Warren, S. 1986, Applied Optics 25, 2650")')
  write(*,'("  - Zubko, V. et al. 1996, MNRAS 282,1321")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
  write(*,'("")')
end subroutine manual

