


* Introduction to optool

This tool allows to produce complex dust opacities right from the
command line. It is derived from Michiel Min's [[https://dianaproject.wp.st-andrews.ac.uk/data-results-downloads/fortran-package/][OpacityTool]] for the
[[https://dianaproject.wp.st-andrews.ac.uk/][DIANA]] program, and committed to its simplicity. For a more
wide-ranging toolset to produce opacities, check out [[https://github.com/charlenelefevre/SIGMA][SIGMA]], the
/Simple Icy Grain Model for Aggregates/, by Lefévre et
al. (2020), also derived from [[https://dianaproject.wp.st-andrews.ac.uk/data-results-downloads/fortran-package/][OpacityTool]], =optool= uses its
effective medium mixing tool set.

* Capabilities

- fully command line driven, no input files need to be edited
- combining materials through mixing into a complex grain
- built-in materials, but can also be used also external data
- DHS to model shape effects and low-porosity aggregates
- full scattering matrix output in a variety of formats and
  normalizations.

* Terms of use

The code doing the real work of =optool= was adopted and modified from
the publicly available versions of the [[https://dianaproject.wp.st-andrews.ac.uk/data-results-downloads/fortran-package/][OpacityTool]] and [[https://github.com/charlenelefevre/SIGMA][SIGMA]]. I
focused on the interface, on simplicity, and a clean set of
conventions. If you are using this tool, you should give credit to the
papers describing the methods used to compute the opacities, as well
as to the original laboratory papers that published the refractive
index measurements.

- DHS model for irregular grains:  [[https://ui.adsabs.harvard.edu/abs/2005A%26A...432..909M][Min et al. 2005, A&A, 432, 909]]
- DIANA standard Opacities: [[https://ui.adsabs.harvard.edu/abs/2016A%26A...586A.103W][Woitke, Min et al. 2016]]
- SIGMA: Lefévre, Min et al. 2020, A&A (submitted)
- Third party software: [[https://ui.adsabs.harvard.edu/abs/1981ApOpt..20.3657T][Toon et al. 1981, Applied Optics 20, 3657]]
- References to refractive index data used in your particular
  application.

* Acknowledgments
- [[http://michielmin.nl/][Michiel Min]] for the [[https://dianaproject.wp.st-andrews.ac.uk/data-results-downloads/fortran-package/][DIANA OpacityTool]] and all the incredible work
  that went into it. =optool= is a direct derivative of that tool and
  resuses almost all of its code.
- [[https://www.researchgate.net/profile/Charlene_Lefevre][Charléne Lefévre]] for [[https://github.com/charlenelefevre/SIGMA][SIGMA]]. =Optool= uses the generalized Bruggeman
  solver from SIGMA's code base.
- [[http://www.ita.uni-heidelberg.de/~dullemond/index.shtml?lang=en][Kees Dullemond]] for his python plotting routine =viewarr= ([[https://github.com/dullemond/interactive_plot][available
  on github]]), and code for computing Planck and Rosseland means
  opacities.
- [[https://www.mpia.de/person/32666/1415887][Jeroen Bouwman]] for pointers to refractive index data.
* User Guide
See the [[file:UserGuide.pdf][User Guide]] for more information.
